// JavaScript Document
var album_thumb=new Array();
var album_name=new Array();
n=-1;
n=n+1;
album_thumb[n]="animals_thumb.jpg";
album_name[n]="Animals";
n=n+1;
album_thumb[n]="medi_thumb.jpg";
album_name[n]="Mediterranean";
n=n+1;
album_thumb[n]="sea_thumb.jpg";
album_name[n]="Sea";
n=n+1;
album_thumb[n]="sports_thumb.JPG";
album_name[n]="Sports";



var im=new Array();
var labels=new Array();
n=-1;
n=n+1;
im[n]="IMG_0739.jpg";
labels[n]="<a href='#' class='label_link'>bench</a><br/><a href='#'>park</a><br/> <a href='#'>person</a><br/><a href='#'>street lamp</a><br/><a href='#'>tree<br/></a><a href='#'>tree</><br/><a href='#'>tree</a><br/><a href='#'>woman</a>";
n=n+1;
im[n]="IMG_2118.JPG";
labels[n]="chair occluded<br/>chair occluded<br/>chair occluded<br/>door crop<br/>filing cabinet<br/>floor<br/>flowers<br/>jacket<br/>picture crop<br/>scarf<br/>table occluded<br/>vase<br/>wall<br/>wall<br/>window<br/>window crop<br/>window";
n=n+1;
im[n]="IMG_2120.JPG";
labels[n]="car<br/>chimney<br/>door<br/>fence<br/>fire hydrant<br/>house<br/>I do not know<br/>road<br/>satellite dish<br/>satellite dish<br/>shrubs<br/>tree<br/>window<br/>window<br/>window";
n=n+1;
im[n]="IMG_2121.JPG";
labels[n]="ceiling<br/>floor<br/>television<br/> tv<br/>wall<br/>wall<br/>wall";
n=n+1;
im[n]="IMG_2128.jpg";
labels[n]="chair<br/>curtain<br/>curtain<br/>door<br/>door<br/>handle<br/>heater<br/>lamp<br/>lightswitch<br/>>plant<br/>table<br/table<br/>thermostat<br/>window";
n=n+1;
im[n]="IMG_2146.jpg";
labels[n]="bench<br/>park<br/> person<br/>street lamp<br/>tree<br/>tree<br/>tree<br/>woman";
n=n+1;
im[n]="IMG_2148.jpg";
labels[n]="chair occluded<br/>chair occluded<br/>chair occluded<br/>door crop<br/>filing cabinet<br/>floor<br/>flowers<br/>jacket<br/>picture crop<br/>scarf<br/>table occluded<br/>vase<br/>wall<br/>wall<br/>window<br/>window crop<br/>window";
n=n+1;
im[n]="IMG_2117.JPG";
labels[n]="car<br/>chimney<br/>door<br/>fence<br/>fire hydrant<br/>house<br/>I do not know<br/>road<br/>satellite dish<br/>satellite dish<br/>shrubs<br/>tree<br/>window<br/>window<br/>window";;
n=n+1;
im[n]="IMG_0749.JPG";
labels[n]="Branch<br/>Dog<br/> Field<br/> Grass<br/>Pathway<br/>Person<br/> Tree<br/>";
n=n+1;
im[n]="IMG_0750.jpg";
labels[n]="chair<br/>curtain<br/>curtain<br/>door<br/>door<br/>handle<br/>heater<br/>lamp<br/>lightswitch<br/>>plant<br/>table<br/table<br/>thermostat<br/>window";
n=n+1;
im[n]="IMG_0752.jpg";
labels[n]="bench<br/>park<br/> person<br/>street lamp<br/>tree<br/>tree<br/>tree<br/>woman";
n=n+1;
im[n]="IMG_0756.jpg";
labels[n]="ceiling<br/>floor<br/>television<br/> tv<br/>wall<br/>wall<br/>wall";


var Animalsim=new Array();
n=-1;
n=n+1;
Forestim[n]="IMG_1406.jpg";
n=n+1;
Forestim[n]="IMG_1407.jpg";
n=n+1;
Forestim[n]="IMG_1408.jpg";
n=n+1;
Forestim[n]="IMG_1409.jpg";
n=n+1;
Forestim[n]="IMG_1410.jpg";
n=n+1;
Forestim[n]="IMG_1411.jpg";
n=n+1;
Forestim[n]="IMG_1412.jpg";
n=n+1;
Forestim[n]="IMG_1413.jpg";
n=n+1;
Forestim[n]="IMG_1414.jpg";

var Peopleim=new Array();
n=-1;
n=n+1;
Peopleim[n]=DSC01446.jpg;
Peopleim[n]=IMG_0919.jpg;
Peopleim[n]=IMG_1454.jpg;
Peopleim[n]=IMG_1455.jpg;
Peopleim[n]=IMG_1457.jpg;

